name: Run TrafficWatch Scraper

on:
  schedule:
    # Runs every day at 11:00 and 15:00 UTC (adjust for your timezone)
    - cron: '0 11 * * *'
    - cron: '0 15 * * *'
    - cron: '0 22 * * *'
  workflow_dispatch:  # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the scraper
      run: |
        python traffic_scraper.py
